#포트설정
server:
  port: '8081'

#JSP설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#SMTP설정
  mail:
    host: smtp.gmail.com
    port: '587'
    username: jhwon48@gmail.com
    password: athr eojl ayoe nrfv
    properties:
      mail:
        debug: 'true'
        smtp:
          connectiontimeout: '5000'
          auth: 'false'
          starttls:
            enable: 'true'
            required: 'true'